### PR TITLE
cpq1,cpq2, lista de desejos em casamento, inicio de multi - linguagens

### PR DESCRIPTION
**Pull request by dragoso**
Rev 1 para linguas_> adicionado arquivo de "LinguaConstants" para todo campo string da source. 

CPQ FULL 1 E 2

### CODE REVIEW

**Comment by kraytos123** [comment]
Its not working missing:

setCarnivalParty

setCarnival

getCarnival

**Comment by dragoso** [comment]
SetCarnivalParty = setEnymies

SetCarnival = setMonsterCarnival

GetCarnival = getMonsterCarnival

**Comment by kraytos123** [comment]
setEnemy and getRoom showing as errors

**Comment by dragoso** [comment]
https://cdn.discordapp.com/attachments/350831332609359876/552962161085906954/unknown.png
https://cdn.discordapp.com/attachments/350831332609359876/552962271228461066/unknown.png
https://cdn.discordapp.com/attachments/350831332609359876/552962298570997760/unknown.png
https://cdn.discordapp.com/attachments/350831332609359876/552962481283137557/unknown.png
https://cdn.discordapp.com/attachments/350831332609359876/552962999833460737/unknown.png

get pull for my repository with modifications 

https://github.com/dragoso/HeavenMS

**Comment by kraytos123** [comment]
Dude please help with this:

https://i.imgur.com/WnATqRc.png

**Comment by kraytos123** [comment]
Its the last error that i have, please help i want to see your assume work :)

https://i.imgur.com/WnATqRc.png

**Comment by dragoso** [comment]
Send me menssage in discord
Dragohe4rt#5202

**Comment by kraytos123** [comment]
Please accept my friend request.

**Pull request merged**
