### PR TITLE
Fix wrong NPC locations

### PR DESCRIPTION
**Pull request by MedicOP**
https://github.com/ronancpl/HeavenMS/issues/312

### CODE REVIEW

**Comment by ronancpl** [comment]
image

There seems to have no issue with NPC positions.

Also, reextracting XML content should be irrelevant for PR'ing... Sorry for the inconvenience, closing this.

**Comment by MedicOP** [comment]
What does this mean? The WZ files I'm using are different from yours?

**Comment by marcuswoon** [comment]
medic you using latest wz files? last update was 7 jan 2019

**Comment by ronancpl** [comment]
Ah, my bad.

Indeed, last Map.wz update dates from 7 jan 2019, as it shows here on GitHub.

However, the current_wz from the Drive did not get updated properly due to some oversight. Solving this now.

**Comment by ronancpl** [comment]
Other wz's files are alright, just Map.wz went missing.

**Comment by ronancpl** [comment]
Confirmed here, wz's are supposed to be synced with Drive.

image

**Comment by marcuswoon** [comment]
sorry, so we need to export to server xml files?

**Comment by ronancpl** [comment]
Should you have NPC location issues with the latest revision, yes.

**Pull request closed without merging**
