### PR TITLE
Fix ClassCastException in 9201045

### PR DESCRIPTION
**Pull request by MedicOP**
I don't know if this is just because I use Java 8, but the line gives me ClassCastException: Cannot cast Long to Integer

This PR should fix that

### CODE REVIEW

**Comment by ronancpl** [comment]
ClassCastException is being thrown because Java 8 is being used.

This PR will be merged now, but on this development please consider using Java 7, as fixes involving solutions for Java 8 will not be considered (and probably closed as well).

**Comment by MedicOP** [comment]
Unfortunately I have other software running on this machine that requires Java 8, and I'd rather not go through the hassle of installing 2 different versions

**Comment by ronancpl** [comment]
Editing _launch.bat_ to specifically use the Java7 artifact should solve the issue:

```
@echo off
@title HeavenMS
SET PATH=C:\Program Files\Java\jdk1.7.0_79\bin;%PATH%
set CLASSPATH=.;dist\*
java -Xmx2048m -Dwzpath=wz\ net.server.Server
pause
```

**Comment by MedicOP** [comment]
I'm on CentOS

**Comment by ronancpl** [comment]
Well, generally speaking, a polite way to solve that environment vars conflict would be to get a command script to set the environments just for this specific purposes (server standalone or IDE, latter one assuming you're running the server through it).

**Comment by MedicOP** [comment]
am using java 7 now :+1:

**Pull request merged**
