### PR TITLE
Fix client crash when entering portal from 800030000

### PR DESCRIPTION
**Pull request by dic1911**
I'm not sure, but this fixes the crash I encountered when on my way from JP entry(800000000 - Zipangu - Mushroom Shrine) to 801000000 - Zipangu - Showa Town

### CODE REVIEW

**Comment by ronancpl** [comment]
That portal is actually intended to lead to "Showa Street 3" (mapid 801030000).

Consider recheck your wz and XML files, as the issue seems related to the boss existing therein, more specifically related to missing boss HPBar.

Take note the XML files from the "wz" folder must be a **reflection** of the wz used client-side. Try regenerating your XML's (assuming you're using clean v83 wz's clientside), doing that should fix the problem found.

**Comment by dic1911** [comment]
Just saying though, I do checked the Map.wz I used in client, the value of the portal teleports to "801030000", which matches to the value that this source set(and that's expected as I downloaded the wz from that Google drive link you put in README.md), however it still crashed, any other possible cause?

**Comment by ronancpl** [comment]
Are you using the wz's from "current_wz"? From that one folder should be ok on the current source.

The other folder "commit203_wz" should be used for whoever is using the source at it's latest "release tag" (https://github.com/ronancpl/HeavenMS/releases/tag/rev203 - from 1 year ago).

A new release tag is currently off the table, as results from developments dating from the latest year are still being studied.

**Comment by dic1911** [comment]
Yes, I'm using wz files from current_wz folder

**Comment by ronancpl** [comment]
Redownloaded those files, no issues found traversing that portal.

**Comment by ronancpl** [comment]
Have you tried to access the area through other means, such as through "!warp 800030000" or from the portal at "Showa Street 2"?

**Pull request closed without merging**
