### PR TITLE
Don't allow @goto in event maps

### PR DESCRIPTION
**Pull request by MedicOP**
I don't think it is intended

### CODE REVIEW

**Comment by ronancpl** [comment]
Um, this is actually an intended feature... When someone tries to change maps through any command (!warp 200000000, !goto orbis), it's expected to them to target non-event maps, as this code depicts.

```
            MapleMap target = c.getChannelServer().getMapFactory().getMap(Integer.parseInt(params[0]));
            if (target == null) {
                player.yellowMessage("Map ID " + params[0] + " is invalid.");
                return;
            }
            
            // expedition issue with this command detected thanks to Masterrulax
            player.saveLocationOnWarp();
            player.changeMap(target, target.getRandomPlayerSpawnpoint());
```

Exceptions to this should be when there is a specific target map (such as "__this map__ the player currently is").

**Comment by MedicOP** [comment]
This isn't about the target map, it's about the map the player is currently in. You shouldn't be able to use @goto to warp out of a PQ or whatever

**Comment by ronancpl** [comment]
Can't see the point of this, since players still could get off the PQ normally then issue a goto command freely.

**Comment by MedicOP** [comment]
You can't use a VIP teleport rock while in a PQ, so why should you be able to use the @goto command? 

Also why is it that !warp does have this check even though it's a GM command, but the donator version of the command does not?

**Comment by MedicOP** [comment]
I do understand your point though of being able to exit the PQ and then use the command. The decision is up to you of course

**Comment by ronancpl** [comment]
I mean, I appreciate your initiative over this matter, and indeed there's a minor hitch when using those command inside PQs (such as that double fade-in fade-out on screen).

Since that happens and the VIP rock block happens, decision has been made to merge.

**Pull request merged**
