### PR TITLE
Fix Dojo loadMapFromWz NPE

### PR DESCRIPTION
**Pull request by MedicOP**
https://github.com/ronancpl/HeavenMS/issues/344

### CODE REVIEW

**Comment by ronancpl** [comment]
Is there any confirmation where `stage + i > 38`?

There are known issues from the XML data provider returning nulls within `source.getData(mapName)` on loadMapFromWz.

**Comment by MedicOP** [comment]
image
image
The highest mu lung dojo map is 925033804

**Comment by ronancpl** [comment]
Max mapid achievable by code:
dojoBaseMap = 925030000
dojoDelta = (100 * (stage + i))

Assuming the max mapid encountered 925033804.
_max_(dojoStageBaseid) = 925030000 + 100 * (38)
_max_(stage + i) = 38

That addition seems to have no effect.

The underlying issue probably has to do with the XML provider. It unreliably returns nulls for existing mapid entries in not-so-often cases... To date trying to figure out why this happens.

**Comment by ronancpl** [comment]
Ok, case confirmed.

There is also another code section that needs care, it's in freeDojoSectionIfEmpty(). Could you also apply that check there?

**Comment by MedicOP** [comment]
oops i messed up the 2nd commit lol

**Comment by MedicOP** [comment]
made a new PR https://github.com/ronancpl/HeavenMS/pull/351

**Pull request closed without merging**
